/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.EnemyToUI;

/**
 *
 * @author alvaro
 */
public class EnemyStarShipView extends javax.swing.JPanel {
    
    private DamageView damageView;
    private LootView lootView;
    
    /**
     * Creates new form EnemyStarShipView
     */
    public EnemyStarShipView() {
        initComponents();
        
        PanelLoot.setVisible(true);
        PanelDamage.setVisible(true);
        
        lootView = new LootView();
        damageView = new DamageView();
        
        PanelLoot.add(lootView);        
        PanelDamage.add(damageView);
    }
    
    void setEnemy(EnemyToUI enemy){
        valorFire.setText(Float.toString(enemy.getAmmoPower()));
        valorShield.setText(Float.toString(enemy.getShieldPower()));
        valorName.setText(enemy.getName());
        
        lootView.setLoot(enemy.getLoot());
        damageView.setDamage(enemy.getDamage());
               
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelName = new javax.swing.JLabel();
        LabelAmmoPower = new javax.swing.JLabel();
        LabelShieldPower = new javax.swing.JLabel();
        valorName = new javax.swing.JLabel();
        valorFire = new javax.swing.JLabel();
        valorShield = new javax.swing.JLabel();
        PanelLoot = new javax.swing.JPanel();
        PanelDamage = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("EnemyStarShip"));

        LabelName.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        LabelName.setText("-Nombre Enemigo:");

        LabelAmmoPower.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        LabelAmmoPower.setText("-Potencia de disparo:");

        LabelShieldPower.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        LabelShieldPower.setText("-Potencia de escudo:");

        valorName.setText("name");

        valorFire.setText("fire");

        valorShield.setText("shield");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelLoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelShieldPower)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorShield))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAmmoPower)
                                    .addComponent(LabelName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorName)
                                    .addComponent(valorFire))))
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName)
                    .addComponent(valorName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAmmoPower)
                    .addComponent(valorFire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelShieldPower)
                    .addComponent(valorShield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelLoot, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAmmoPower;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelShieldPower;
    private javax.swing.JPanel PanelDamage;
    private javax.swing.JPanel PanelLoot;
    private javax.swing.JLabel valorFire;
    private javax.swing.JLabel valorName;
    private javax.swing.JLabel valorShield;
    // End of variables declaration//GEN-END:variables
}
