/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.LootToUI;

/**
 *
 * @author alvaro
 */
public class LootView extends javax.swing.JPanel {

    /**
     * Creates new form LootView
     */
    public LootView() {
        initComponents();
    }

    void setLoot(LootToUI loot) {
        valor_armas.setText(Integer.toString(loot.getnWeapons()));
        valor_escudos.setText(Integer.toString(loot.getnShields()));
        valor_hangar.setText(Integer.toString(loot.getnHangars()));
        valor_fuel.setText(Integer.toString(loot.getnSupplies()));
        valor_medallas.setText(Integer.toString(loot.getnMedals()));

        if (loot.isGetEfficient()) {
            valor_transformacion.setText("Estación Eficiente");
        } else if (loot.isSpaceCity()) {
            valor_transformacion.setText("Ciudad Espacial");
        } else {
            valor_transformacion.setText("No");
        }
        
        repaint();
        revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelWeapons = new javax.swing.JLabel();
        LabelShields = new javax.swing.JLabel();
        LabelHangar = new javax.swing.JLabel();
        LabelFuel = new javax.swing.JLabel();
        LabelMedals = new javax.swing.JLabel();
        LabelTransform = new javax.swing.JLabel();
        valor_armas = new javax.swing.JLabel();
        valor_escudos = new javax.swing.JLabel();
        valor_hangar = new javax.swing.JLabel();
        valor_fuel = new javax.swing.JLabel();
        valor_medallas = new javax.swing.JLabel();
        valor_transformacion = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder("Loot"));

        LabelWeapons.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        LabelWeapons.setText("-Weapons:");

        LabelShields.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        LabelShields.setText("-Shields:");

        LabelHangar.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        LabelHangar.setText("-Hangar size:");

        LabelFuel.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        LabelFuel.setText("-Fuel:");

        LabelMedals.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        LabelMedals.setText("-Medals:");

        LabelTransform.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        LabelTransform.setText("-Transform:");

        valor_armas.setText("armas");

        valor_escudos.setText("escudos");

        valor_hangar.setText("hangar");

        valor_fuel.setText("fuel");

        valor_medallas.setText("medallas");

        valor_transformacion.setText("transformar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelHangar)
                            .addComponent(LabelWeapons))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valor_armas)
                            .addComponent(valor_hangar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelShields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(valor_escudos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTransform)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valor_transformacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelFuel)
                            .addComponent(LabelMedals))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valor_medallas)
                            .addComponent(valor_fuel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelWeapons)
                    .addComponent(LabelFuel)
                    .addComponent(valor_fuel)
                    .addComponent(valor_armas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelShields)
                    .addComponent(LabelMedals)
                    .addComponent(valor_medallas)
                    .addComponent(valor_escudos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHangar)
                    .addComponent(LabelTransform)
                    .addComponent(valor_hangar)
                    .addComponent(valor_transformacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFuel;
    private javax.swing.JLabel LabelHangar;
    private javax.swing.JLabel LabelMedals;
    private javax.swing.JLabel LabelShields;
    private javax.swing.JLabel LabelTransform;
    private javax.swing.JLabel LabelWeapons;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel valor_armas;
    private javax.swing.JLabel valor_escudos;
    private javax.swing.JLabel valor_fuel;
    private javax.swing.JLabel valor_hangar;
    private javax.swing.JLabel valor_medallas;
    private javax.swing.JLabel valor_transformacion;
    // End of variables declaration//GEN-END:variables
}
