/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alvaro
 */
public class NamesCapture extends javax.swing.JDialog {
    
    private ArrayList<String> names = new ArrayList<>();

    /**
     * Creates new form NamesCapture
     */
    public NamesCapture(MainWindow parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo (null);
        setTitle (parent.getAppName());
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                // Se decide que cancelar la entrada de nombres supone no iniciar la aplicación
                System.exit(0);
            }
        });
        
    }
    
    ArrayList<String> getNames() {
        setVisible(true);
        return names;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_primer_nombre = new javax.swing.JLabel();
        Label_segundo_nombre = new javax.swing.JLabel();
        Label_tercer_nombre = new javax.swing.JLabel();
        Label_cuarto_nombre = new javax.swing.JLabel();
        Label_advertencia = new javax.swing.JLabel();
        TextField_primer_nombre = new javax.swing.JTextField();
        TextField_segundo_nombre = new javax.swing.JTextField();
        TextField_tercer_nombre = new javax.swing.JTextField();
        TextField_cuarto_nombre = new javax.swing.JTextField();
        Button_empezar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Label_primer_nombre.setText("Nombre 1:");

        Label_segundo_nombre.setText("Nombre 2:");

        Label_tercer_nombre.setText("Nombre 3:");

        Label_cuarto_nombre.setText("Nombre 4:");

        Label_advertencia.setFont(new java.awt.Font("Fira Sans Semi-Light", 2, 12)); // NOI18N
        Label_advertencia.setText("(Rellenar minimo los dos primeros recuadros)");

        TextField_primer_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_primer_nombreActionPerformed(evt);
            }
        });

        TextField_segundo_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_segundo_nombreActionPerformed(evt);
            }
        });

        Button_empezar.setText("Empezar");
        Button_empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_empezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_advertencia)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Button_empezar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Label_segundo_nombre)
                                .addComponent(Label_primer_nombre)
                                .addComponent(Label_tercer_nombre)
                                .addComponent(Label_cuarto_nombre))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextField_primer_nombre)
                                .addComponent(TextField_segundo_nombre)
                                .addComponent(TextField_tercer_nombre)
                                .addComponent(TextField_cuarto_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_advertencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_primer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_primer_nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_segundo_nombre)
                    .addComponent(TextField_segundo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_tercer_nombre)
                    .addComponent(TextField_tercer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_cuarto_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_cuarto_nombre))
                .addGap(18, 18, 18)
                .addComponent(Button_empezar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_primer_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_primer_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_primer_nombreActionPerformed

    private void TextField_segundo_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_segundo_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_segundo_nombreActionPerformed

    private void Button_empezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_empezarActionPerformed
        // TODO add your handling code here:
        names.clear();
        
        if(TextField_primer_nombre.getText().length() != 0){
            names.add(TextField_primer_nombre.getText());
        }
        
        if(TextField_segundo_nombre.getText().length() != 0){
            names.add(TextField_segundo_nombre.getText());
        }
        
        if(TextField_tercer_nombre.getText().length() != 0)
            names.add(TextField_tercer_nombre.getText());
        
        if(TextField_cuarto_nombre.getText().length() != 0)
            names.add(TextField_cuarto_nombre.getText());
            
        if(names.size() < 2)
            JOptionPane.showMessageDialog(this, "Error con el numero de jugadores introducido.", MainWindow.getInstance().getAppName(), JOptionPane.ERROR_MESSAGE);
        else{
            dispose();
        }
    }//GEN-LAST:event_Button_empezarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_empezar;
    private javax.swing.JLabel Label_advertencia;
    private javax.swing.JLabel Label_cuarto_nombre;
    private javax.swing.JLabel Label_primer_nombre;
    private javax.swing.JLabel Label_segundo_nombre;
    private javax.swing.JLabel Label_tercer_nombre;
    private javax.swing.JTextField TextField_cuarto_nombre;
    private javax.swing.JTextField TextField_primer_nombre;
    private javax.swing.JTextField TextField_segundo_nombre;
    private javax.swing.JTextField TextField_tercer_nombre;
    // End of variables declaration//GEN-END:variables
}
